function objSeg = srv_limb_to_segment(attachIndices, limbs, palm)
    % number of inputs must be exactly 3
    narginchk(3, 3);

	% type checking on inputs
    ...

	% compute the segment
    objSeg = [];
    if ~isempty(attachIndices),
        linkNo = attachIndices(1);
        limbNo = attachIndices(2);
        selectedLimb = limbs(limbNo);
        objSeg = Limb(selectedLimb.Z(:,1:linkNo), ...
                      selectedLimb.P(:,1:linkNo), ...
                      llcs_homogeneous(srv_a2noa(selectedLimb.Z(:,linkNo)), selectedLimb.P(:,linkNo)), ...
                      'joints', selectedLimb.joints(1:linkNo), ...
                      'name', selectedLimb.name, ...
                      'manuf', selectedLimb.manuf, ...
                      'comment', selectedLimb.comment);
    end